In [1]:
# 正式答案Part1
import numpy as np
import numpy.linalg as LA

def vector_norm(n):
    origin_vec = np.arange(1, n+1, 1)
    x = 1/np.square(origin_vec) #计算各元素的平方
    y = np.square(origin_vec)
    print('当 n = ' + str(n) + ' 时：')
    #print(x)
    print('x向量的无穷范数为：' + str(LA.norm(x, ord=np.inf)))  # 无穷范数
    print('x向量的1范数为：' + str(LA.norm(x, ord=1)))  # 1范数
    print('x向量的2范数为：' + str(LA.norm(x, ord=2)))  # 2范数
    #print(y)
    print('y向量的无穷范数为：' + str(LA.norm(y, ord=np.inf)))  # 无穷范数
    print('y向量的1范数为：' + str(LA.norm(y, ord=1)))  # 1范数
    print('y向量的2范数为：' + str(LA.norm(y, ord=2)))  # 2范数
    print('\n')

if __name__=='__main__':
    vector_norm(100)
    vector_norm(1000)
    vector_norm(10000)

当 n = 100 时：
x向量的无穷范数为：1.0
x向量的1范数为：1.6349839001848931
x向量的2范数为：1.0403474925929668
y向量的无穷范数为：10000.0
y向量的1范数为：338350.0
y向量的2范数为：45280.60655512468


当 n = 1000 时：
x向量的无穷范数为：1.0
x向量的1范数为：1.6439345666815601
x向量的2范数为：1.0403476502488507
y向量的无穷范数为：1000000.0
y向量的1范数为：333833500.0
y向量的2范数为：14159814.028909419


当 n = 10000 时：
x向量的无穷范数为：1.0
x向量的1范数为：1.6448340718480603
x向量的2范数为：1.0403476504086528
y向量的无穷范数为：100000000.0
y向量的1范数为：333383335000.0
y向量的2范数为：4472694974.3229




In [2]:
# 正式答案Part2
import numpy as np
import numpy.linalg as LA

def vector_norm_new(n):
    origin_vec = np.arange(1, n+1, 1)
    # x = 1/(origin_vec)**2
    # y = origin_vec ** 2
    x = 1/np.square(origin_vec) #计算各元素的平方
    x_new = x[::-1] #x倒序输出，避免大数吃小数
    y = np.square(origin_vec)
    #print(x_new)
    print('当 n = ' + str(n) + ' 时：')
    print('修正后x向量的无穷范数为：' + str(LA.norm(x_new, ord=np.inf)))  # 无穷范数
    print('修正后x向量的1范数为：' + str(LA.norm(x_new, ord=1)))  # 1范数
    print('修正后x向量的2范数为：' + str(LA.norm(x_new, ord=2)))  # 2范数
    #print(y)
    print('y向量的无穷范数为：' + str(LA.norm(y, ord=np.inf)))  # 无穷范数
    print('y向量的1范数为：' + str(LA.norm(y, ord=1)))  # 1范数
    print('y向量的2范数为：' + str(LA.norm(y, ord=2)))  # 2范数
    print('\n')

if __name__=='__main__':
    vector_norm_new(100)
    vector_norm_new(1000)
    vector_norm_new(10000)

当 n = 100 时：
修正后x向量的无穷范数为：1.0
修正后x向量的1范数为：1.634983900184893
修正后x向量的2范数为：1.0403474925929668
y向量的无穷范数为：10000.0
y向量的1范数为：338350.0
y向量的2范数为：45280.60655512468


当 n = 1000 时：
修正后x向量的无穷范数为：1.0
修正后x向量的1范数为：1.64393456668156
修正后x向量的2范数为：1.0403476502488505
y向量的无穷范数为：1000000.0
y向量的1范数为：333833500.0
y向量的2范数为：14159814.028909419


当 n = 10000 时：
修正后x向量的无穷范数为：1.0
修正后x向量的1范数为：1.6448340718480596
修正后x向量的2范数为：1.040347650408653
y向量的无穷范数为：100000000.0
y向量的1范数为：333383335000.0
y向量的2范数为：4472694974.3229




In [3]:
# 正式答案Part1
import numpy as np
from math import*

# 秦九韶算法函数
def QinJiuShao(a, x):
    # a是多项式系数数组，顺序为x次数增大
    n = len(a) - 1
    s = [i for i in range(len(a))]
    s[n] = a[n]
    while n >= 1:
        s[n-1] = s[n] * x + a[n-1]
        n -= 1
    return s[0]

# 牛顿迭代法求根
def Newton(eps):
    a1 = [-512, 2304, -4608, 5376, -4032, 2016, -672, 144, -18, 1]
    a2 = [2304, -9216, 16128, -16128, 10080, -4032, 1008, -144, 9]
    x=[]
    x.append(1.5)
    err = abs(QinJiuShao(a1,x[-1])) #最新加的x在最后
    number_iteration=0
    while err>eps:
        x.append(x[-1]-QinJiuShao(a1, x[-1])/QinJiuShao(a2, x[-1]))  #x k+1
        err=abs(QinJiuShao(a1, x[-1]))
        number_iteration=number_iteration+1
    print('精度为%s时，牛顿法迭代次数为%d次'%(eps, number_iteration)) #格式化输出
    print('方程的根x*为%s'%(x[-1]))
    print('f(x*)的值为%s'%(QinJiuShao(a1, x[-1])))
Newton(5e-5)
Newton(5e-6)
Newton(5e-7)

精度为5e-05时，牛顿法迭代次数为4次
方程的根x*为1.687852461631914
f(x*)的值为-2.8134501462773187e-05
精度为5e-06时，牛顿法迭代次数为6次
方程的根x*为1.7533649114167382
f(x*)的值为-3.3767138347684522e-06
精度为5e-07时，牛顿法迭代次数为8次
方程的根x*为1.8051277674800874
f(x*)的值为-4.0527470446249936e-07


In [4]:
# 正式答案Part2
# 牛顿下山法求根
def NewtonDown(eps):
    x=[]
    x.append(1.5)#初始值
    a1 = [-512, 2304, -4608, 5376, -4032, 2016, -672, 144, -18, 1]
    a2 = [2304, -9216, 16128, -16128, 10080, -4032, 1008, -144, 9]
    fx=abs(QinJiuShao(a1, x[-1]))
    number_iteration=0
    F=[]
    F.append(fx)
    L=[]
    df=QinJiuShao(a1, x[-1])/QinJiuShao(a2, x[-1])
    while fx>eps:  #与误差值比较
        lambd=1
        df=QinJiuShao(a1, x[-1])/QinJiuShao(a2, x[-1])
        x1=x[-1]-lambd*df
        fx=abs(QinJiuShao(a1, x1))
        number_iteration=number_iteration+1#叠加次数
        while fx>=F[-1]:    #与上一个比较
            lambd=lambd/2
            x1=x[-1]-lambd*df  #x k+1
            fx=abs(QinJiuShao(a1, x1))
            number_iteration=number_iteration+1
        F.append(fx)
        x.append(x1)
        L.append(lambd)
    print('精度为%s时，牛顿下山法迭代次数为%d次'%(eps, number_iteration))
    print('方程的根x*为', x[-1])
    print('f(x*)的值为', F[-1])
NewtonDown(5e-5)
NewtonDown(5e-6)
NewtonDown(5e-7)

精度为5e-05时，牛顿下山法迭代次数为4次
方程的根x*为 1.687852461631914
f(x*)的值为 2.8134501462773187e-05
精度为5e-06时，牛顿下山法迭代次数为6次
方程的根x*为 1.7533649114167382
f(x*)的值为 3.3767138347684522e-06
精度为5e-07时，牛顿下山法迭代次数为8次
方程的根x*为 1.8051277674800874
f(x*)的值为 4.0527470446249936e-07


In [5]:
# 正式答案Part3
#二分法求根
left=1.5
right=2.5
eps=5e-5
number_iteration=0
a=[-512, 2304, -4608, 5376, -4032, 2016, -672, 144, -18, 1]
f_left=QinJiuShao(a,left)
x=(left+right)/2
f=QinJiuShao(a,x)
while right-left>eps:
    if f*f_left>0:
        left=x
        x=(left+right)/2
        number_iteration=number_iteration+1
    elif f*f_left<0:
        right=x
        x=(left+right)/2
        number_iteration=number_iteration+1
    else:
        number_iteration=number_iteration+1
        break
print(x)
print(number_iteration)

2.0
1


In [6]:
# LU分解法通用程序
from numpy import *

def lu_decomp(A):
    m,n = A.shape
    if m != n:
        return
    temp_A = A.copy()
    L = eye(n)
    U = zeros((m,n))
    for k in range(0,n-1):
        for i in range(k+1,n):
            if abs(temp_A[i,k]) > 1.0e-9:
                lam = temp_A[i,k] / temp_A[k,k]
                temp_A[i,k+1:n] = temp_A[i,k+1:n] - lam * temp_A[k,k+1:n]
                temp_A[i,k] = 0
                L[i,k] = lam
    U[:n,:n] = temp_A[:n,:n]
    return L,U
A = array([[2,1,1,0],[4,3,3,1],[8,7,9,5],[6,7,9,8]])
lu_decomp(A)

(array([[1., 0., 0., 0.],
        [2., 1., 0., 0.],
        [4., 3., 1., 0.],
        [3., 4., 1., 1.]]),
 array([[2., 1., 1., 0.],
        [0., 1., 1., 1.],
        [0., 0., 2., 2.],
        [0., 0., 0., 2.]]))

In [7]:
# PLU分解法通用程序，目前L的计算有问题，待修改
def plu_decomp(A):
    m,n = A.shape
    if m != n:
        return
    temp_A = A.copy()
    L = eye(n)
    P = eye(n)
    U = zeros((m,n))
    index = [i for i in range(n-1)]
    for k in range(0,n-1):
        print(k)
        index_k = argmax(abs(temp_A[k:n,k]))+k
        if(index_k != k):
            for j in range(n):
                temp_A[index_k,j],temp_A[k,j] = temp_A[k,j],temp_A[index_k,j]
                P[index_k,j],P[k,j] = P[k,j],P[index_k,j]
                #if k+1<n:
                #    L[index_k+1,j],L[k+1,j] = L[k+1,j],L[index_k+1,j]
                temp_A[index[k],j],temp_A[k,j] = temp_A[k,j],temp_A[index[k],j]
                P[index[k],j],P[k,j] = P[k,j],P[index[k],j]
                #print(temp_A)
        for i in range(k+1,n):
            if abs(temp_A[i,k]) > 1.0e-9:
                lam = temp_A[i,k] / temp_A[k,k]
                temp_A[i,k:n] = temp_A[i,k:n] - lam * temp_A[k,k:n]
                #print(lam)
                #print(temp_A)
                #temp_A[i,k+1:n] = temp_A[i,k+1:n] - lam * temp_A[k,k+1:n]
                #temp_A[i,k] = 0
                L[i,k] = lam
                print(L)
        U[k:n,k:n] = temp_A[k:n,k:n]
    return P,L,U
A = array([[2.,1.,1.,0.],[4.,3.,3.,1.],[8.,7.,9.,5.],[6.,7.,9.,8.]])#结果正确
#A = array([[0.,-6.,-1.],[1.,2.,2.],[2.,-2.,1.]])
plu_decomp(A)

0
[[1.  0.  0.  0. ]
 [0.5 1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]
[[1.   0.   0.   0.  ]
 [0.5  1.   0.   0.  ]
 [0.25 0.   1.   0.  ]
 [0.   0.   0.   1.  ]]
[[1.   0.   0.   0.  ]
 [0.5  1.   0.   0.  ]
 [0.25 0.   1.   0.  ]
 [0.75 0.   0.   1.  ]]
1
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.25       -0.42857143  1.          0.        ]
 [ 0.75        0.          0.          1.        ]]
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.25       -0.42857143  1.          0.        ]
 [ 0.75       -0.28571429  0.          1.        ]]
2
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.25       -0.42857143  1.          0.        ]
 [ 0.75       -0.28571429  0.33333333  1.        ]]


(array([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.5       ,  1.        ,  0.        ,  0.        ],
        [ 0.25      , -0.42857143,  1.        ,  0.        ],
        [ 0.75      , -0.28571429,  0.33333333,  1.        ]]),
 array([[ 8.        ,  7.        ,  9.        ,  5.        ],
        [ 0.        ,  1.75      ,  2.25      ,  4.25      ],
        [ 0.        ,  0.        , -0.85714286, -0.28571429],
        [ 0.        ,  0.        ,  0.        ,  0.66666667]]))